# Nom de l'application
spring.application.name=square-users

# Port du serveur
server.port=8081

# Base H2 en mémoire (indispensable ici pour activer l'auto-configuration du servlet)
spring.datasource.url=jdbc:h2:mem:test_square_users_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activation explicite de la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration JWT (clé secrète d'au moins 256 bits et durée en millisecondes : 24h = 86400000)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000