# Base H2 en mémoire
spring.datasource.url = jdbc:h2:mem:test_square_users_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate pour H2 (recréé les tables à chaque démarrage)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console Web H2 (accessible sur http://localhost:8081/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console