# Nom de l'application
spring.application.name=square-users

# Changement de port pour éviter le conflit avec square-games (8080)
server.port=8081

# PROFIL ACTIF : change ici 'h2' par 'postgres' selon ton besoin !
spring.profiles.active=h2

